services:
  vehicle-service:
    build: 
      context: ./vehicle-service
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./vehicle-service:/app
    networks:
      - car-network
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=your_secret_key
  vehicle-db:
    image: postgres:15
    container_name: vehicle-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: vehicle_db
    depends_on:
      - kafka
    networks:
      - car-network
    ports:
      - "5432:5432"
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - car-network
  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: dev-local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_METRICS_PORT: 9997
      DYNAMIC_CONFIG_ENABLED: true
    depends_on:
      - "kafka"
    networks:
      - car-network
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
    networks:
      - car-network
  rent-service:
    build:
      context: ./rent-service/
    container_name: rent-service
    restart: unless-stopped
    depends_on:
      - rent-db
    ports:
      - "3002:3002"
    environment:
      SERVER_PORT: 3002
      DATASOURCE_URL: jdbc:postgresql://rent-db:5433/rent_db
      DATASOURCE_USERNAME: postgres
      DATASOURCE_PASSWORD: POSTGRES_PASSWORD
      JWT_SECRET_KEY: ZTNiMGM0NDI5OGZjMWMxNDlhZmJmNGM4OTk2ZmI5MjQyN2FlNDFlNDY0OWI5MzRjYTQ5NTk5MWI3ODUyYjg1NQ==
      SPRING_DEVTOOLS_REMOTE_SECRET: my_secret_key
    volumes:
      - ./rent-service:/app
    networks:
      - car-network
  rent-db:
    image: postgres:15
    container_name: rent-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: POSTGRES_PASSWORD
      POSTGRES_DB: rent_db
    command: -p 5433
    ports:
      - "5433:5433"
    networks:
      - car-network
  payment-service:
    build:
      context: ./payment-service/
    container_name: payment-service
    environment:
      SPRING_DEVTOOLS_REMOTE_SECRET: my_secret_key
    ports:
      - "3003:3003"
    networks:
      - car-network
    volumes:
      - ./payment-service:/app
networks:
  car-network:
    external: true
