apiVersion: skaffold/v4beta3
kind: Config
manifests:
  rawYaml:
    - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mtks/starrent-account-service
      context: accounts-service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "./src/**/*.ts"
            dest: .
    # - image: mtks/starrent-vechile-service
    #   context: vechile-service
    #   docker:
    #     dockerfile: Dockerfile
    #   sync:
    #     manual:
    #       - dest: .
    #         src: ./src/**/*.java
