apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: car-rent.com
      http:
        paths:
          - path: /api/accounts/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: account-depl
                port:
                  number: 3000
          - path: /api/v1/?(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: vechile-depl
                port:
                  number: 3001
