services:
  mongo:
    image: mongo:latest
    container_name: mongo-srv
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_PASSWORD_FILE: /run/secrets/mongodb_root_password
      MONGO_INITDB_ROOT_USERNAME_FILE: /run/secrets/mongodb_root_username
      MONGO_INITDB_DATABASE: admin
      MONGO_USERNAME_FILE: /run/secrets/mongodb_username
      MONGO_PASSWORD_FILE: /run/secrets/mongodb_password
      MONGO_DATABASE: accounts
    restart: always
    volumes:
      - ./mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongo-data:/data/db

    secrets:
      - mongodb_root_password
      - mongodb_root_username
      - mongodb_password
      - mongodb_username

  app:
    build: .
    container_name: accounts-srv
    volumes:
      - .:/usr/src/app
    depends_on:
      - mongo
    ports:
      - '3000:3000'
    command: npm run start:dev
    environment:
      - NODE_ENV=development
      - JWT_KEY=test123
    secrets:
      - mongodb_password
      - mongodb_username
volumes:
  mongo-data:

secrets:
  mongodb_root_password:
    file: ./secrets/.mongodb_root_password
  mongodb_root_username:
    file: ./secrets/.mongodb_root_username
  mongodb_password:
    file: ./secrets/.mongodb_password
  mongodb_username:
    file: ./secrets/.mongodb_username
