services:
  vehicles:
    build:
      context: .
    container_name: app
    restart: unless-stopped
    ports:
      - '3001:3001'
    volumes:
      - ./:/app
    environment:
      - SPRING_DEVTOOLS_REMOTE_SECRET=your_secret_key